/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const IValidatablePropertyType = t.union(t.lit("number"), t.lit("integer"), t.lit("string"), t.lit("boolean"), t.lit("array"), t.lit("null"), t.lit("object"));

export const IValidatableProperty = t.iface([], {
  "type": "IValidatablePropertyType",
  "nullable": t.opt("boolean"),
  "minLength": t.opt("number"),
  "maxLength": t.opt("number"),
  "required": t.opt("boolean"),
});

export const IValidatableProperties = t.iface([], {
  [t.indexKey]: "IValidatableProperty",
});

const exportedTypeSuite: t.ITypeSuite = {
  IValidatablePropertyType,
  IValidatableProperty,
  IValidatableProperties,
};
export default exportedTypeSuite;
